[DATA-364] Get orbslam binary for integration tests
viamrobotics/rdk pull request #1380
Opened 2022-09-26 13:45 UTC by tessavitabile

2022-09-27 13:23 UTC, tessavitabile commented on .github/workflows/main.yml
> +    uses: viamrobotics/rdk/.github/workflows/test.yml@DATA-364
Will revert before merging

2022-09-27 13:23 UTC, tessavitabile commented on .github/workflows/pullrequest.yml
> +    uses: viamrobotics/rdk/.github/workflows/test.yml@DATA-364
Will revert before merging

2022-09-27 13:23 UTC, tessavitabile commented on services/slam/builtin/builtin.go
> +		if slamSvc.slamProcessLogReader != nil {
I also have this fix in https://github.com/viamrobotics/rdk/pull/1377

2022-09-27 13:23 UTC, tessavitabile commented on services/slam/builtin/orbslam_int_test.go
> -	// TODO DATA-364: remove this check
I decided to leave this check in place, so that local tests that don't have an orbslam binary (e.g. on a mac) skip this test.

2022-09-27 19:51 UTC, tessavitabile commented
I just merged https://github.com/viamrobotics/rdk/pull/1377, which added the full integration tests, so I rebased here to re-run the tests. Tests are now timing out, which I believe it because we're so close to the 10min limit, and the integration tests are on the longer side, since they run orbslam. Do you think it's possible to run these tests for rdk changes (and increase the 10min limit), or will we need to run them only for slam changes?

2022-09-28 13:35 UTC, tessavitabile commented
From this run, we see that orblsam integration tests took 1m7s to run: https://github.com/viamrobotics/slam/actions/runs/3140663794/jobs/5102291852

2022-09-28 15:08 UTC, tessavitabile commented
Getting some hang shutting down the slam process, converting back to draft.

2022-09-28 18:46 UTC, Otterverse requested changes
So I don't believe this test belongs in our normal test suite the way you've integrated it here. Integration with external programs that are huge like this really should be isolated from our basic unit tests and run on their own. This is doubly true because the slam server is not open source, while RDK now is.

Now, this is my opinion, and I'm willing to be talked out of it, but to me, I think it'd make a lot more sense for this to be handled similar to how the E2E tests are, and run as a separate job from the main unit tests.

2022-09-28 18:48 UTC, tessavitabile commented
That sounds fine to me! Especially considering the test runtime concerns Eric just brought up.

2022-09-29 14:09 UTC, tessavitabile commented on services/slam/builtin/orbslam_int_test.go
> -	// TODO DATA-364: remove this check
This also allows the test to be skipped in the "Build and Test" job.

2022-09-29 23:04 UTC, Otterverse approved these changes
LGTM!

2022-09-30 13:04 UTC, merged