[DATA-501] File not found error when TFLite model is not found
viamrobotics/rdk pull request #1415
Opened 2022-09-30 16:20 UTC by kharijarrett

Improving the error message so it's clear when the loader fails because the file isn't where it was looking.

2022-10-01 13:36 UTC, bhaney requested changes
Nice, thanks for the change! Just add a test for this, where you expect to see the file not find error, and then it will be good to merge.

2022-10-01 13:47 UTC, bhaney commented on services/vision/builtin/tflite_detector.go
> +			return nil, errors.Wrapf(err, "file not found at %s", filepath)
can you also find a way to "expand" this filepath to the full path? using function https://pkg.go.dev/path/filepath#Abs

2022-10-03 16:14 UTC, bhaney approved these changes
LGTM! One last question below about also calling Abs when first loading the model

2022-10-03 16:29 UTC, kharijarrett commented on services/vision/builtin/tflite_detector.go
>  	model, err = loader.Load(filepath)
Yeah actually just added... it might help when ppl forget the full path (but we should still encourage them to put the full path)

2022-10-03 16:29 UTC, bhaney commented on services/vision/builtin/tflite_detector.go
> +	fullpath, err2 := fp.Abs(filepath)
Check err2 before calling Load()

2022-10-03 16:34 UTC, bhaney approved these changes

2022-10-03 16:37 UTC, bhaney commented
Ah one more thing- what about tflite_classifier?

2022-10-03 18:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/viamrobotics/rdk?pullRequest=1415) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/viamrobotics/rdk?pullRequest=1415) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/viamrobotics/rdk?pullRequest=1415) it.</sub>

2022-10-03 19:13 UTC, merged