[Rsdk-572] fix readings for all movement sensor, return errors for unimplemented methods
viamrobotics/rdk pull request #1420
Opened 2022-09-30 21:38 UTC by randhid

Now returning unimplemented methods for movement sensors that don't implement those methods.  Doesn't hang usb 

Warning added from nmea parser (what causes a nil gps location) that will look like: 
![Screenshot 2022-09-30 at 17 21 11](https://user-images.githubusercontent.com/35934754/193358493-3e60721f-91ff-4ead-871e-494af92483eb.png)

2022-10-03 16:12 UTC, maximpertsov requested changes

2022-10-03 16:12 UTC, maximpertsov commented on components/movementsensor/utils.go
> +}
I think it's better to just define concrete error for each kind of unimplemented method. This gives us compile-time checks against misspells.

e.g. 

```
var ErrMethodUnimplementedPosition = errors.New("Position Unimplemented")
var ErrMethodUnimplementedOrientation = return errors.New("Orientation Unimplemented")

// etc
```

2022-10-03 17:22 UTC, randhid commented on components/movementsensor/gpsnmea/gpsnmea.go
> +	if cfg.Board == "" && cfg.ConnectionType == i2cStr {
yeah I was testing on my laptop for the wit imu/gps

2022-10-03 18:50 UTC, maximpertsov commented on components/movementsensor/gpsnmea/serial.go
> +	return g.data.fixQuality, nil
discussed IRL - last captured error shouldn't really be a factor if read fix is returned successfully

2022-10-03 18:51 UTC, maximpertsov commented on components/movementsensor/gpsnmea/serial.go
> +	return map[string]float32{"hDOP": float32(g.data.hDOP), "vDOP": float32(g.data.vDOP)}, nil
makes sense, we can leave nil - sounds similar to https://github.com/viamrobotics/rdk/pull/1420#discussion_r986116796

2022-10-03 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/viamrobotics/rdk?pullRequest=1420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/viamrobotics/rdk?pullRequest=1420) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/viamrobotics/rdk?pullRequest=1420) it.</sub>

2022-10-03 19:35 UTC, randhid commented on components/movementsensor/gpsnmea/nmeaParser.go
> +}
missed this but updated code on my side.

2022-10-04 15:36 UTC, maximpertsov commented on components/movementsensor/movementsensor.go
> +	if err != nil && err.Error() != ErrMethodUnimplementedPosition.Error() {
nit, i think it's more idiomatic to do this

```suggestion
	if err != nil && errors.Is(err, ErrMethodUnimplementedPosition) {
```

2022-10-04 15:37 UTC, maximpertsov commented on components/movementsensor/movementsensor.go
> +	if err != nil && err.Error() != ErrMethodUnimplementedLinearVelocity.Error() {
```suggestion
	if err != nil && errors.Is(err, ErrMethodUnimplementedLinearVelocity) {
```

2022-10-04 15:37 UTC, maximpertsov commented on components/movementsensor/movementsensor.go
> +	if err != nil && err.Error() != ErrMethodUnimplementedAngularVelocity.Error() {
```suggestion
	if err != nil && errorsIs(err, ErrMethodUnimplementedAngularVelocity) {
```

2022-10-04 15:38 UTC, maximpertsov commented on components/movementsensor/movementsensor.go
> +	if err != nil && err.Error() != ErrMethodUnimplementedCompassHeading.Error() {
```suggestion
	if err != nil && errors.Is(err, ErrMethodUnimplementedCompassHeading) {
```

2022-10-04 15:38 UTC, maximpertsov commented on components/movementsensor/movementsensor.go
> +	if err != nil && err.Error() != ErrMethodUnimplementedOrientation.Error() {
```suggestion
	if err != nil && errors.Is(err, ErrMethodUnimplementedOrientation) {
```

2022-10-04 18:22 UTC, maximpertsov approved these changes

2022-10-04 20:35 UTC, merged