Add rdk representation of worldstate along with conversion methods
viamrobotics/rdk pull request #1622
Opened 2022-11-28 16:26 UTC by raybjork

This PR removes `commonpb.WorldState` from most of the codebase and replaces it with `referenceframe.WorldState` a representation that is more easily usable with existing RDK functions.

2022-11-28 16:50 UTC, biotinker commented on referenceframe/worldstate.go
> +	Transforms                   []*commonpb.Transform
PoseInFrame, not static frame, sorry

2022-11-29 21:34 UTC, biotinker commented on referenceframe/transformable.go
> +	protoTransforms := make([]*commonpb.Transform, 0)
nit: Should be `make([]*commonpb.Transform, 0, len(poseSlice))`

2022-11-29 21:35 UTC, biotinker commented on referenceframe/transformable.go
> +	transforms := make([]*PoseInFrame, 0)
nit: Should be `make([]*PoseInFrame, 0, len(proto))`

2022-11-29 21:41 UTC, biotinker approved these changes
Two small nits, then LGTM

2022-11-29 21:54 UTC, raybjork commented on referenceframe/worldstate.go
> +	Transforms                   []*commonpb.Transform
Done

2022-11-30 18:03 UTC, gvaradarajan requested changes

2022-11-30 20:14 UTC, raybjork commented on robot/framesystem/service_test.go
> +	transforms := []*referenceframe.PoseInFrame{
Thanks!

2022-11-30 20:17 UTC, raybjork commented on referenceframe/transformable.go
> +func PoseInFrameSliceFromTransformProtobuf(protoSlice []*commonpb.Transform) ([]*PoseInFrame, error) {
changed

2022-11-30 20:19 UTC, raybjork commented on referenceframe/transformable.go
> +		if err != nil {
done

2022-11-30 22:59 UTC, gvaradarajan approved these changes

2022-12-01 14:29 UTC, merged