Update model json files for grippers
viamrobotics/rdk pull request #1638
Opened 2022-12-05 18:11 UTC by nfranczak

This PR updates model json files for VG1 and fake gripper.
The geometry for fake gripper is the same as the geometry for VG1.

2022-12-05 19:10 UTC, raybjork approved these changes

2022-12-05 19:13 UTC, biotinker commented
Rather than adding a geometry to the fake gripper, let's remove its model file entirely; that way, users can more easily use it to model any arbitrary gripper.

It only has a model file in the first place, due to some now-obsolete testing that was done back in 2021.

2022-12-06 20:13 UTC, biotinker requested changes
Re-posting this comment as actual review feedback.

Rather than adding a geometry to the fake gripper, let's remove its model file entirely; that way, users can more easily use it to model any arbitrary gripper.

It only has a model file in the first place, due to some now-obsolete testing that was done back in 2021.

2022-12-06 21:01 UTC, nfranczak commented on components/gripper/fake/gripper.go
> +			var g gripper.LocalGripper = &Gripper{Name: config.Name, model: nil}
gotcha, will change now

2022-12-06 21:02 UTC, nfranczak commented on components/gripper/fake/gripper.go
> +			var g gripper.LocalGripper = &Gripper{Name: config.Name, model: nil}
ah, I do not think that is allowed. I am getting:
```
cannot use &(Gripper literal) (value of type *Gripper) as referenceframe.Model value in struct literal: *Gripper does not implement referenceframe.Model (missing method AlmostEquals)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)
```

2022-12-06 21:13 UTC, biotinker commented on components/gripper/fake/gripper.go
> +			var g gripper.LocalGripper = &Gripper{Name: config.Name, model: nil}
Is that from a build or a test?

Also; we should actually be removing the `model` from the `Gripper` struct entirely for `fake`, and returning `nil` explicitly like in other grippers. Example from the softrobotics gripper:

```
// ModelFrame is unimplemented for softGripper.
func (g *softGripper) ModelFrame() referenceframe.Model {
	return nil
}
```

2022-12-07 15:34 UTC, nfranczak commented on components/gripper/fake/gripper.go
> +			var g gripper.LocalGripper = &Gripper{Name: config.Name, model: nil}
I error showed up right when I pasted `&Gripper{Name: config.Name}` into the model field.
Not an issue anymore as I removed the model field from the fake gripper struct per your request.

2022-12-07 15:56 UTC, biotinker approved these changes
This LGTM, though some changes to some unrelated json files snuck in here; those should be reverted

2022-12-13 20:23 UTC, merged