RSDK-856 Add a default timeout to all inbound gRPC methods
viamrobotics/rdk pull request #1852
Opened 2023-02-08 22:23 UTC by benjirewis

RSDK-856

Adds a default context timeout for all inbound gRPC methods of 10 minutes using a new unary interceptor. Tests that the context is modified when no deadline is declared and that the context remains untouched when a deadline is already declared.

2023-02-08 22:25 UTC, benjirewis commented on robot/web/web_test.go
> -	iRobot.(*inject.Robot).StatusFunc = func(ctx context.Context, resourceNames []resource.Name) ([]robot.Status, error) {
@cheukt pointed out that these lines were a noop and likely an accidental copy of the ones directly above.

2023-02-09 15:04 UTC, cheukt commented
@edaniels would that not also set a time limit for the stream? which I assume we wouldn't want

2023-02-09 15:09 UTC, cheukt reviewed
we should also add the same interceptor to the module startup process (around L335)

2023-02-09 15:47 UTC, benjirewis commented
Server stream interceptors do not take a context and instead share a context across the stream (see `Context()` method on [`ServerStream`](https://pkg.go.dev/google.golang.org/grpc#ServerStream)). I could, however, modify the context created in [`CreateFromIncomingContext()`](https://github.com/viamrobotics/rdk/blob/v0.2.15/operation/web.go#L82); that should add a timeout to all inbound methods whether streaming of unary. I think that might also handle your concern about the module startup process, @cheukt .

2023-02-09 20:52 UTC, benjirewis commented
Discussed offline with @cheukt; seems like we're unsure whether the strategy above would work. Just added the same interceptor to the module startup process with more tests for now.

2023-02-09 21:08 UTC, cheukt requested changes
looks good! we can DRY it a little

2023-02-09 21:08 UTC, cheukt commented on robot/web/web.go
> +	unaryInterceptors = append(unaryInterceptors, func(
since the two interceptor functions are the same, we can factor it out

2023-02-09 21:54 UTC, cheukt approved these changes
LGTM!

2023-02-09 22:26 UTC, merged