RSDK 893 refresh in checkConnection when needed
viamrobotics/rdk pull request #1889
Opened 2023-02-16 19:49 UTC by purplenicole730

2023-02-16 21:11 UTC, cheukt requested changes
we should also add tests `TestClientRefresh` should be a good base. We want to make sure that we're only calling `ResourceNames` and `ResourceRPCSubtypes` once per refresh cycle

2023-02-16 21:11 UTC, cheukt commented on robot/client/client.go
> +				if refresh == true {
linter error here

2023-02-17 19:32 UTC, cheukt commented on robot/client/client.go
> +	if refreshTime > 0 {
nvm, misread

2023-02-21 16:13 UTC, purplenicole730 commented on robot/client/client_test.go
> +	test.That(t, callCountNames, test.ShouldEqual, 6)
I'm not entirely sure why `callCountSubtypes` and `callCountNames` are different. I thought they would be the same, but repeated runs of the tests show that these are the values.

2023-02-23 18:03 UTC, cheukt commented on robot/client/client_test.go
> +		dur = 100 * time.Millisecond
rm

2023-02-23 18:03 UTC, cheukt commented on robot/client/client_test.go
> +		// block here until ResourceNames is called 6 times
nit: 7

2023-02-23 18:34 UTC, cheukt approved these changes

2023-02-23 18:41 UTC, merged