RSDK-1945 Add DoCommand to all relevant services
viamrobotics/rdk pull request #1912
Opened 2023-02-22 19:39 UTC by benjirewis

RSDK-1945

Adds `DoCommand` functionality to DataManager, Motion, Navigation, Sensors, Shell, SLAM and Vision services. For each of these services:
- Adds `generic.Unimplemented` to builtin service
- Adds `DoCommand` to `client.go` to invoke new service-specific gRPC endpoint
- Adds `DoCommand` to `server.go` to receive new gRPC requests
- Adds `resource.Generic` to the service interface
- Adds test of `DoCommand` functionality in `client_test.go`
- Adds an injectable `DoCommandFunc` to relevant inject service

2023-02-22 19:43 UTC, benjirewis commented on examples/customresources/models/mynavigation/mynavigation.go
> +	generic.Unimplemented
L26 of this file asserts that `navSvc` implements the `navigation.Service` interface that now includes `resource.Generic`.

2023-02-22 19:43 UTC, benjirewis commented on services/shell/client_test.go
> +package shell_test
The Shell service had no pre-existing `client_test`. I added one, but it only tests `DoCommand` functionality.

2023-02-22 19:43 UTC, benjirewis commented on testutils/inject/shell_service.go
> +package inject
The Shell service had no pre-existing injectable implementation in `inject`. I added one, but it has no injection function for `Shell`.

2023-02-22 19:58 UTC, cheukt requested changes
looks good! can you add a test in each server_test and service_test as well?

2023-02-22 21:25 UTC, benjirewis commented on services/datamanager/server_test.go
> +	test.That(t, respMap["command"], test.ShouldResemble, "test")
Annoyingly, `test.That(t, resp, test.ShouldResemble, generic.TestCommand)` fails because somewhere the `int` 500 is converted to a `float64`.

2023-02-22 21:25 UTC, benjirewis commented on services/shell/server_test.go
> +package shell_test
The Shell service had no pre-existing `server_test`. I added one, but it only tests `DoCommand` functionality.

2023-02-22 22:45 UTC, cheukt approved these changes
LGTM!

2023-02-23 18:02 UTC, purplenicole730 approved these changes

2023-02-23 18:54 UTC, merged