RSDK-2003 Move AttrConf from builtin.go to slam
viamrobotics/rdk pull request #1994
Opened 2023-03-06 21:38 UTC by zaporter-work

Ticket: https://viam.atlassian.net/browse/RSDK-2003

This should only be done after https://github.com/viamrobotics/slam/pull/159

2023-03-06 22:14 UTC, kkufieta approved these changes
LGTM mod nit

2023-03-06 22:26 UTC, nicksanford requested changes

2023-03-06 22:26 UTC, nicksanford commented on services/slam/builtin/builtin.go
> +	minDataRateMsec               = 200
Also, should `minDataRateMsec` still be in builtin.go?

Your PR to move code into the slam repo appears to not use it: https://github.com/viamrobotics/slam/pull/159#pullrequestreview-1327281919

2023-03-06 22:27 UTC, nicksanford approved these changes
LGTM as long as we know whether or not we should remove `minDataRateMs` or not.

2023-03-07 14:33 UTC, tessavitabile approved these changes
Yes, in https://github.com/viamrobotics/slam/pull/159, I said it's fine to remove the cap on data rate, since it's doing more harm than good. Zack resolved the ticket here: https://viam.atlassian.net/browse/RSDK-1922

2023-03-07 16:05 UTC, merged