RSDK-2313 add slam service name to motionRequest proto message
viamrobotics/rdk pull request #2045
Opened 2023-03-10 22:04 UTC by raybjork

This pull request implements updates RDK to match the proto message defined in [this pull request](https://github.com/viamrobotics/api/pull/216)

2023-03-13 22:42 UTC, spieswl commented on testutils/inject/motion_service.go
> +	MoveSingleComponentFunc func(
Nice catch

2023-03-13 22:44 UTC, spieswl approved these changes
LGTM

2023-03-13 22:46 UTC, spieswl requested changes

2023-03-13 22:46 UTC, spieswl commented on go.mod
> +replace go.viam.com/api => github.com/raybjork/api v0.0.0-20230310213510-f207dfec088c
Dont forget to clean this one up.

2023-03-14 00:03 UTC, raybjork commented on go.mod
> +replace go.viam.com/api => github.com/raybjork/api v0.0.0-20230310213510-f207dfec088c
Yes will remember for sure!

2023-03-14 18:37 UTC, merged