Use refactored external auth config for managed robots
viamrobotics/rdk pull request #2046
Opened 2023-03-12 00:07 UTC by edaniels

This ends up consuming the changes in app and https://github.com/viamrobotics/goutils/pull/145 and https://github.com/viamrobotics/api/pull/217

2023-03-12 00:20 UTC, edaniels commented on robot/web/web.go
> +	if options.Auth.ExternalAuthConfig != nil {
This is the most important part of the PR.

2023-03-16 21:59 UTC, michaellee1019 requested changes

2023-03-16 22:34 UTC, edaniels commented on go.mod
> +replace go.viam.com/api => /Users/eric/api
well yes :)

2023-03-16 22:34 UTC, edaniels commented on go.mod
> +replace go.viam.com/api => /Users/eric/api
please approve PR though beyond that since ill remove these as other prs get in. CI wont pass anyway

2023-03-16 22:34 UTC, edaniels commented on grpc/dial.go
> +		return "app.viaminternal:8089", true, true
app.viaminternal is always supposed to be secure. idk why this changed

2023-03-16 22:34 UTC, edaniels commented on robot/web/web.go
>  	}
mhm!

2023-03-16 22:54 UTC, michaellee1019 commented on go.mod
> +replace go.viam.com/api => /Users/eric/api
Yes np i was waiting to understand Qs in other comments :)

2023-03-16 22:54 UTC, michaellee1019 approved these changes

2023-03-18 00:12 UTC, cheukt approved these changes
LGTM

2023-03-20 14:18 UTC, merged