change default mimeType
viamrobotics/rdk pull request #2179
Opened 2023-04-07 14:14 UTC by Rob1in

Fulfill the logic of having the server dealing with the MimeType

2023-04-07 14:49 UTC, bhaney requested changes
Rather than replace the hint, I think you can just remove the line

2023-04-07 14:49 UTC, bhaney commented on components/camera/client.go
>  	streamCtx, stream, frameCh := gostream.NewMediaStreamForChannel[image.Image](cancelCtxWithMIME)
I would say just remove the entire line, and just do 
`streamCtx, stream, frameCh := gostream.NewMediaStreamForChannel[image.Image](c.cancelCtx)`

2023-04-07 14:51 UTC, bhaney commented on components/camera/client.go
>  	streamCtx, stream, frameCh := gostream.NewMediaStreamForChannel[image.Image](cancelCtxWithMIME)
Oh actually never mind, you're right to do what you're doing. Because the context in Stream might have a MIMETypeHint itself.

2023-04-07 14:52 UTC, bhaney approved these changes
Nevermind, I see now that we want to capture if `ctx` has a mime type hint in it

2023-04-10 20:54 UTC, Rob1in commented
Making a new commit because a test was failing. If the requested mime type is  `""`,  the server checks the camera properties to decide how to encode (JPEG for a ColorStream for instance). Since the injected camera didn't have a PropertiesFunc, it was panicking when looking for properties. To avoid this, adding a `MimeTypeRawRGBA ` to the context passed to` ReadImage()`.

2023-04-10 21:30 UTC, Rob1in commented
Making changes because tests were failing. If the requested mime type is "", the server checks the camera properties to decide how to encode (JPEG for a ColorStream for instance). Since the injected camera didn't have a PropertiesFunc, it was panicking when looking for properties. To avoid this, adding a MimeTypeRawRGBA to the context passed to ReadImage().

2023-04-11 13:53 UTC, edaniels commented
the PR title seems off, can you update it?

2023-04-11 15:58 UTC, bhaney approved these changes

2023-04-11 17:47 UTC, merged