RSDK-2962 - SLAM UI does not resize well
viamrobotics/rdk pull request #2322
Opened 2023-05-03 22:35 UTC by nfranczak

We now display the full screen when on a larger computer monitor.

2023-05-03 22:35 UTC, nfranczak commented on web/frontend/src/components/slam-2d-render.vue
> -//
remove un-need line

2023-05-03 22:35 UTC, nfranczak commented on web/frontend/src/components/slam.vue
> +      <div class="gap-4x border-border-1 w-full justify-start sm:border-l">
this is all it took for it to be full screen

2023-05-03 22:36 UTC, nfranczak commented on web/frontend/src/components/slam-2d-render.vue
> -    class="pcd-container relative w-full"
removed pcd-container because that had no visual effect

2023-05-03 22:36 UTC, nfranczak commented on web/frontend/src/components/slam.vue
> +  filterResources(props.resources, 'rdk', 'component', 'base') !== undefined) && updatedDest);
only allow user to click move if they've clicked a destination.

2023-05-03 22:37 UTC, nfranczak commented on web/frontend/src/components/slam.vue
> -  if (updatedDest === false) {
this will now no longer be hit because of how we construct `moveClick`

2023-05-04 13:04 UTC, EshaMaharishi commented
Thanks so much @nfranczak for getting a fix up for this quickly! Just a heads up I am removing myself from the review since I think Nick, Jeremy, and Micheal are in a better position to review

2023-05-04 13:43 UTC, nicksanford requested changes
Thanks for putting together a fix for the UI issue so quickly!!! Could you please move any code unrelated to fixing that issue into another PR (with a ticket for what it does)?

2023-05-04 13:44 UTC, nicksanford commented
@nfranczak could you please add it in a branch with the same name as the ticket, link to the ticket in the PR description, and please make sure you are not submitting 55 commits for a few line change?

2023-05-04 14:14 UTC, closed without merging