RSDK-2960 - Fix order of execution for 2D slam ui when first loaded or refreshed
viamrobotics/rdk pull request #2333
Opened 2023-05-05 20:39 UTC by nfranczak

When we refresh it is always the case that we the watch method the pose is triggered before the watch method for pointclouds. Hence, we need to re-add the base/destination marker to ensure that it renders on top of the updated pointcloud.

2023-05-05 20:39 UTC, nfranczak commented on web/frontend/src/components/slam-2d-render.vue
> -  scene.clear();
removed because we already cleared the object we wanted to get rid of.

2023-05-05 20:55 UTC, nicksanford requested changes

2023-05-05 20:55 UTC, nicksanford commented on web/frontend/src/components/slam-2d-render.vue
> +    scene.add(destinationMarker);
1. Why do we need to re add them?
2. Where are they being removed from the scene?

2023-05-08 14:23 UTC, nicksanford requested changes

2023-05-08 14:23 UTC, nicksanford commented on web/frontend/src/components/slam-2d-render.vue
> +    scene.add(destinationMarker);
Let's confirm with @micheal-parks whether or not this is the right way to do this.

I would be kinda surprised if the only way to render a three.js entity behind another is to re add every entity that needs to be in front of it.

2023-05-08 14:25 UTC, nicksanford commented on web/frontend/src/components/slam-2d-render.vue
> +    scene.add(destinationMarker);
Sry, didn't see your comment before I posted my last one @micheal-parks .

2023-05-09 20:26 UTC, closed without merging

2023-05-09 21:08 UTC, jeremyrhyde reviewed
Questions on updatePose removal/marker existence checks

2023-05-09 21:08 UTC, jeremyrhyde commented on web/frontend/src/components/slam-2d-render.vue
> -  if (props.pose !== undefined) {
[q] This removal is because we don't need to check the pose as it will always exist (since the marker is created at the beginning). Correct?

2023-05-09 21:08 UTC, jeremyrhyde commented on web/frontend/src/components/slam-2d-render.vue
> +  if (destinationMarker !== undefined) {
[q] in what situation could the `destinationMarker` be undefined?