[RSDK-3364] fake.json Number of Resources Unit Test
viamrobotics/rdk pull request #2495
Opened 2023-06-09 19:28 UTC by 8ashar

I added a unit test to validate the number of resources created on a server based on /etc/configs/fake.json and added two helper functions to the robottestutils package.

2023-06-09 19:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/viamrobotics/rdk?pullRequest=2495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/viamrobotics/rdk?pullRequest=2495) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: micheal-parks<br/>:x: Bashar Eid<br/><hr/>**Bashar Eid** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/viamrobotics/rdk?pullRequest=2495) it.</sub>

2023-06-09 19:54 UTC, cheukt commented
prefer pr name format of "RSDK-3364 - XXXX", also can you rename the pr to be more clear about what you're adding to the codebase?

2023-06-09 20:43 UTC, cheukt reviewed
just commenting since I'll be OOO so don't block merge on me, but two things to address

2023-06-09 20:43 UTC, cheukt commented on web/server/entrypoint_test.go
> +	cfgFilename := "./../../etc/configs/fake.json"
use `rdkutils.ResolveFile` to resolve this file

2023-06-12 16:08 UTC, njooma requested changes

2023-06-12 16:08 UTC, njooma commented on web/server/entrypoint_test.go
> +	cfgFilename := utils.ResolveFile("./") + "/etc/configs/fake.json"
you can use `ResolveFile` to resolve the entire path, not just the `./` part:

```go
cfgFilename := utils.ResolveFile("etc/configs/fake.json")
```

2023-06-13 18:43 UTC, njooma approved these changes

2023-06-13 18:44 UTC, merged