[RSDK-3649] Create the obstacles_distance vision model
viamrobotics/rdk pull request #2578
Opened 2023-06-26 19:58 UTC by vpandiarajan20

2023-06-29 21:53 UTC, vpandiarajan20 commented on services/vision/obstacledistance/obstacle_distance.go
> +			// if p.X != 0 || p.Y != 0 {
The points from the ultrasonic sensor camera should always be (0, 0, dist)

2023-06-29 21:54 UTC, vpandiarajan20 commented on services/vision/obstacledistance/obstacle_distance.go
> +		sphere, err := spatialmath.NewSphere(pt, 0.1, "obstacle") // can't make it zero because of error case in newsphere
Not sure if I should override or if this is an acceptable workaround

2023-06-29 21:54 UTC, vpandiarajan20 commented on services/vision/obstacledistance/obstacle_distance.go
> +		// implementation of kalman filter (smart smoothing average function) over readings from nextpointcloud
for future PR

2023-07-05 14:33 UTC, vpandiarajan20 commented on services/vision/obstacledistance/obstacle_distance.go
> +			// if p.X != 0 || p.Y != 0 {
Not necessary, to be removed.

2023-07-05 18:26 UTC, bhaney requested changes
Nice first pass! This looks good, and sounds like it works well given the experiment you've already done. Below are my comments

2023-07-05 18:26 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +		})
You can break early if the total count exceeds NumQueries by returning false if count >= NumQueries.

2023-07-05 18:26 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +			return nil, errors.New("more than one point from one of the readings, expected one")
I think this error should be more descriptive: "obstacles_distance expects only one point in the point cloud from the camera. Underlying camera generates more than 1 point in its point cloud". And then also in the documentation, we will need to be clear about that behavior

2023-07-05 18:26 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +		pt := spatialmath.NewPoint(vector, "obstacle").Pose()
I think you don't have to generate the NewSphere, and can simply use the `pt` in the Geometry field in Object.

2023-07-05 19:26 UTC, vpandiarajan20 commented on services/vision/obstacledistance/obstacle_distance.go
> +	segmenter := func(ctx context.Context, src camera.VideoSource) ([]*vision.Object, error) {
I actually did that initially but I got the following error later:
`cannot use segmenter (variable of type func(ctx context.Context, src camera.Camera) ([]*"go.viam.com/rdk/vision".Object, error)) as segmentation.Segmenter value in argument to svision.NewServicecompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)`

2023-07-05 20:17 UTC, vpandiarajan20 commented
For documentation purposes please pay special attention to the following error:
`obstacles_distance expects only one point in the point cloud from the camera. Underlying camera generates more than 1 point in its point cloud`
This just means that clouds from NextPointCloud should only be returning a singular point in their cloud, because it's supposed to be just one reading from an ultrasonic sensor or something of the sort, should just be one value.

2023-07-05 21:24 UTC, bhaney requested changes
Nice! Almost done, just a few nit-picks

2023-07-05 21:24 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +	var deps []string
Right now, this is a nil pointer to a string array. You can return an empty slice, which requires you to make it, i.e. deps := make([]string,0) or deps := []string{}

2023-07-05 21:24 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +		return nil, errors.New("object detection config for distance detector cannot be nil")
state "config for obstacle_distance cannot be nil"

2023-07-05 21:24 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +		numPoints += cloudCopy.Size()
Actually, then maybe you should check back when you're doing the original PointCloud gathering ... up on line 73. If pc.Size() != 1, then fail

2023-07-05 21:24 UTC, bhaney commented on services/vision/obstacledistance/obstacle_distance.go
> +		return -1, errors.New("obstacles_distance expects only one point in the point cloud from the camera." +
Move this error up to where you originally request the point clouds

2023-07-06 15:48 UTC, bhaney approved these changes
Nice! LGTM

2023-07-06 18:04 UTC, merged