RSDK-3415: Implement "position only" mode for MoveOnMap and MoveOnGlobe
viamrobotics/rdk pull request #2589
Opened 2023-06-28 16:42 UTC by nthakur7

position-only mode is used when the "motion_profile" field in `extra` has the value of "position_only" and `extra` is a parameter passed to `MoveOnMap`/`MoveOnGlobe`. In this mode, planning will be done without taking into account orientation. This is implemented by creating a planning frame and an execution frame for the kinematic base, where the planning frame either has 2 or 3DOF depending on the planning mode. When executing, the base will not do any extra spins to reach a specific orientation of the waypoint.

2023-06-28 21:06 UTC, nfranczak commented on services/motion/builtin/builtin.go
> +	profile, ok := extra["motion_profile"]
[nit] we should check that extra != nil so there is no nil pointer deference error

2023-06-28 21:06 UTC, nfranczak commented on services/motion/builtin/builtin.go
>  		kb, err = kinematicbase.WrapWithFakeKinematics(ctx, fake, localizer, limits)
[q]: why does fake base not care about being position only?

2023-06-30 15:53 UTC, raybjork requested changes

2023-06-30 15:53 UTC, raybjork commented on referenceframe/model.go
> +		return nil, errors.Errorf("Must have 2DOF state (x, y) to create 2DMobileModelFrame, have %d dof", len(limits))
Good catch fixing the spelling error! We should also update the rest of the error message to be consistent with the new behavior

2023-06-30 15:53 UTC, raybjork commented on services/slam/fake/slam.go
> +		{Min: -2 * math.Pi, Max: 2 * math.Pi},
[minor] We shouldn't be modifying this function here, since SLAM is only ever concerned with 2DOF

2023-06-30 15:53 UTC, raybjork commented on services/motion/builtin/builtin.go
> +		profile, ok := extra["motion_profile"]
preference for `if profile, ok := extra["motion_profile"]; ok {`

2023-06-30 17:10 UTC, biotinker commented on components/base/kinematicbase/kinematics.go
> +			if len(ddk.model.DoF()) == 2 { // 2DOF -> position only mode
It's not fully clear from the code why "if we didn't command the base, and the frame is 2dof, then we should return nil here". I had to trace a bunch of function calls to understand why.

Could we add some comments explaining what's going on here?

2023-06-30 17:12 UTC, biotinker requested changes
This is looking excellent. Nice work.

One small request for some comments on the code, then lgtm

2023-06-30 17:33 UTC, biotinker approved these changes
LGTM, nice work

2023-07-03 14:05 UTC, nfranczak approved these changes

2023-07-03 18:38 UTC, raybjork approved these changes

2023-08-01 18:46 UTC, raybjork approved these changes
Nice job!  Just a couple nits I'd like addressed before merging

2023-08-01 18:46 UTC, raybjork commented on components/base/kinematicbase/differentialDrive.go
> +		ddk.planningFrame, err = referenceframe.New2DMobileModelFrame(b.Name().ShortName(), limits, geometry)
this can just be set to `ddk.executionFrame`

2023-08-01 18:46 UTC, raybjork commented on components/base/kinematicbase/fake_kinematics.go
> +		fk.planningFrame, err = referenceframe.New2DMobileModelFrame(b.Name().ShortName(), limits, geometry)
this can also be just set equal to the executionFrame

2023-08-01 18:46 UTC, raybjork commented on services/motion/builtin/builtin.go
> +			if motionProfile == motionplan.PositionOnlyMotionProfile {
This can be written `kinematicsOptions.PositionOnlyMode = motionProfile == motionplan.PositionOnlyMotionProfile`

2023-08-01 18:46 UTC, raybjork commented on services/motion/builtin/builtin.go
> +			if motionProfile == motionplan.PositionOnlyMotionProfile {
same thing this can become `kinematicsOptions.PositionOnlyMode = motionProfile == motionplan.PositionOnlyMotionProfile`

2023-08-02 20:48 UTC, merged