Adding Transform Camera for Segmentation
viamrobotics/rdk pull request #2636
Opened 2023-07-12 17:42 UTC by vpandiarajan20

Add transform camera to visualize segmentation visual services

2023-07-14 21:07 UTC, bhaney requested changes
Sorry for the delay here! Just some edits on how to initialize the camera. use the original source camera of the whole camera here -it may require you to add some parameters to the switch statement in pipeline.go/transform.go

2023-07-14 21:07 UTC, bhaney commented on components/camera/transformpipeline/segmenter.go
> +	CameraName    string `json:"camera_name"`
Don't put the camera name in the Config, but take it from the original pipeline source. So feed it in as a parameter in `newSegmentationsTransform`

2023-07-14 21:07 UTC, bhaney commented on components/camera/transformpipeline/segmenter.go
> +	return deps, nil
This will be taken care of by the larger transform camera component

2023-07-21 14:59 UTC, bhaney approved these changes
thanks for this! One last thing - could you describe the manual testing you did for this PR, and specifically could you make sure the following things work

1. On the App, a point cloud shows up when you use the segmenter transform
2. When you use a detector transform, it works as normal, and then you try to show the pointcloud on App, an error occurs (as expected) but the app doesn't crash or anything.

2023-07-21 19:48 UTC, vpandiarajan20 commented
![image](https://github.com/viamrobotics/rdk/assets/52717428/1a40be7e-e6d5-48af-9a6b-ccc510989c09)
Tested detector transform

2023-07-26 16:32 UTC, vpandiarajan20 commented
Sample of Transform Camera working
(Segmentation algorithm has been applied)
![image](https://github.com/viamrobotics/rdk/assets/52717428/8e001fdc-41b6-410d-9405-ab1bcf0c360b)

Original PC
![image](https://github.com/viamrobotics/rdk/assets/52717428/15e5380a-79dd-4b25-9d11-6ed31b039724)

2023-07-26 18:22 UTC, merged