RSDK-3314: Update Gripper to support GetGeometries
viamrobotics/rdk pull request #2649
Opened 2023-07-17 19:23 UTC by nthakur7

2023-07-17 19:47 UTC, raybjork commented on components/gripper/fake/gripper.go
> +// Geometries returns TODO
This comment exists several places.  Lets change it to something better

2023-07-19 02:04 UTC, raybjork requested changes
Looking great! I think with some test coverage we'll be there.  Should be enough to just add coverage to the fake gripper model

2023-07-19 16:48 UTC, nthakur7 commented on components/gripper/client.go
>  	"context"
they are updated, are you not able to see it?

2023-07-20 14:41 UTC, raybjork approved these changes

2023-07-20 19:26 UTC, biotinker commented on components/gripper/client.go
>  	"context"
Oh I see. Weirdness with how github displays files. Never mind.

2023-07-20 19:28 UTC, biotinker approved these changes
LGTM

2023-07-21 14:54 UTC, merged