Change units in UR driver to match config field units
viamrobotics/rdk pull request #3002
Opened 2023-09-27 22:56 UTC by randhid

What it says on the tin.

2023-09-27 23:00 UTC, randhid commented on components/arm/universalrobots/ur.go
>  		return nil, errors.New("speed for universalrobots has to be between .1 and 1")
```suggestion
		return nil, errors.New("speed for universalrobots has to be between 18 and 180 degrees per second")
```

2023-09-27 23:00 UTC, randhid commented on components/arm/universalrobots/ur.go
> -	if newConf.Speed > 1 || newConf.Speed < .1 {
Removed repeated validation check.

2023-09-27 23:11 UTC, JessamyT approved these changes
LGTM but I just write things :) Thx for quick fix. I'm already making the docs change so don't worry about that ticket.

2023-09-28 15:37 UTC, oliviamiller approved these changes
lgtm lmk if you want me to test on the UR!

2023-09-28 15:40 UTC, randhid commented
> lgtm lmk if you want me to test on the UR!

Yes please if you have time!

2023-09-28 16:17 UTC, raybjork requested changes
Thanks! Just looking for one change here

2023-09-28 16:17 UTC, raybjork commented on components/arm/universalrobots/ur.go
>  		return nil, errors.New("speed for universalrobots has to be between .1 and 1")
Yeah we'll want to update this

2023-09-28 16:17 UTC, raybjork commented on components/arm/universalrobots/ur.go
> +	if cfg.Speed > 180 || cfg.Speed < 18 {
Can we rename the config parameter to be `SpeedDegsPerSec

2023-09-28 16:17 UTC, raybjork commented on components/arm/universalrobots/ur.go
> -		4.0*ua.speed,
Its concerning that we just weren't doing this to begin with

2023-09-29 00:13 UTC, raybjork approved these changes

2023-10-02 22:43 UTC, merged