RSDK-5658 expand support for URDF files
viamrobotics/rdk pull request #3206
Opened 2023-11-08 19:13 UTC by raybjork

This PR adds functionality to our support of URDF files, allowing us to convert from our internal representation to the URDF version

2023-11-08 19:16 UTC, raybjork commented on spatialmath/geometry.go
> +func NewGeometryConfig(g Geometry) (*GeometryConfig, error) {
Made some changes in this file to rename variables to be more accurate as we no longer have the `gc` (GeometryCreator) type

2023-11-13 17:01 UTC, biotinker requested changes
IMO the URDF stuff should be in its own package somewhere, not in `spatialmath`. They don't implement any spatialmath interfaces, and introduces a specific file format to a library without file formats.

2023-11-13 18:12 UTC, raybjork commented on referenceframe/urdf.go
> -	Collision []struct {
We do, I just moved it to its own object.  Its easier to work with these objects when they are flatter

2023-11-13 22:51 UTC, raybjork commented on spatialmath/box.go
> +func newURDFBox(b *box) *urdfBox {
Refactored

2023-11-13 23:08 UTC, biotinker commented on utils/math.go
> +func MMToMeters(m float64) float64 {
This should probably be `mm float64`

2023-11-13 23:08 UTC, biotinker approved these changes
LGTM, one optional change

2023-11-14 00:29 UTC, merged