RSDK-6426 Initial working adjustment of PTGs to output normalized velocities
viamrobotics/rdk pull request #3482
Opened 2024-01-24 21:17 UTC by biotinker

2024-01-29 17:12 UTC, raybjork requested changes

2024-01-29 17:12 UTC, raybjork commented on components/base/kinematicbase/ptgKinematics.go
> +				utils.SelectContextOrWait(ctx, time.Duration(inputUpdateStep*1000*1000)*time.Microsecond)
have the same nit here

2024-01-29 17:12 UTC, raybjork commented on components/base/kinematicbase/ptgKinematics.go
> +				ptgk.inputLock.Lock()
Are we concerned about the rate at which we'll be switching this mutex?

2024-01-29 17:12 UTC, raybjork commented on components/base/kinematicbase/ptgKinematics.go
> +func (ptgk *ptgBaseKinematics) trajectoryToArcsteps(traj []*tpspace.TrajNode) []arcStep {
Also theres a world where adding these helpers to the tpspace package could make sense.  I'm fine with them being here though. wondering what your thoughts are?

2024-01-29 17:12 UTC, raybjork commented on components/base/kinematicbase/ptgKinematics.go
> +	return finalSteps
I'm having a hard time reviewing this through inspection.  Have you tested this code on hardware?

2024-01-30 14:47 UTC, raybjork commented on components/base/kinematicbase/ptgKinematics.go
> +		timestep := time.Duration(step.timestepSeconds*1000*1000) * time.Microsecond
Oh I had the SI prefixes drilled into my head in middle school so the conversion is simpler when I'm looking at the order of magnitude.  If you did it intentionally and prefer this we can leave it though

2024-01-30 14:50 UTC, raybjork approved these changes

2024-01-30 16:11 UTC, biotinker commented on components/base/kinematicbase/ptgKinematics.go
> +		timestep := time.Duration(step.timestepSeconds*1000*1000) * time.Microsecond
Yeah I mentally count by multiples of a thousand. I really like how the `time` package does it
https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/time/time.go;l=631

2024-01-30 16:12 UTC, merged