[RSDK-6178] Don't allow extremely large fake camera resolutions.
viamrobotics/rdk pull request #3612
Opened 2024-02-27 00:15 UTC by randhid

I confirmed that a resolution of 40000 pixels for width and height causes viam-server to crash on a mac, and no image to be shown on the RC card.

With the new limits in the Validate field we at least guard against bringing up the server and getting it into a state where it cannot shut down cleanly.

Camera can show images with the config:
```
{
  "width": 10000,
  "height": 10000
}
```

<img width="645" alt="Screenshot 2024-02-26 at 19 10 47" src="https://github.com/viamrobotics/rdk/assets/35934754/e7ba0e9d-1e8f-4edc-b92c-0d3d9cb6bb30">

Complains when we go above 10000 and does not show or build the resource
<img width="1447" alt="Screenshot 2024-02-26 at 18 37 46" src="https://github.com/viamrobotics/rdk/assets/35934754/d3b0d8f2-e93c-49f7-ad13-d48f18109d72">

And viam server stops cleanly after a restart or SIGINT.
![Screenshot 2024-02-26 at 19 12 43](https://github.com/viamrobotics/rdk/assets/35934754/ce7089a1-2683-45ad-9fce-e859d350dae0)

Without this Validate check, allowing a fake camera to construct itself with just a fake camera configured at best causes the server to hang on shutdown, or crashes viam-server according to the QA testers.

<img width="1185" alt="Screenshot 2024-02-26 at 19 14 26" src="https://github.com/viamrobotics/rdk/assets/35934754/da7bd982-be99-4298-98ca-59a7552e7287">

2024-02-27 12:27 UTC, hexbabe commented
Probably would add a test that explicitly expects the error with the absurdly large dimensions but according to our conversation about unit tests yesterday I can be swayed either way

2024-02-27 16:11 UTC, seanavery approved these changes
LGTM

2024-02-27 16:45 UTC, randhid commented
> Probably would add a test that explicitly expects the error with the absurdly large dimensions but according to our conversation about unit tests yesterday I can be swayed either way

So, for Config and Validation, the useful tests are in `resource.go` and `config.go` but i can add a in-driver test. The screenshots show the results of manual testing.

There is a crazy behavior where the resource construction seems to loop forever with a bad validation when I was expecting just five failures. I think that's because of the `resource.AlwaysRebuild` and cameras not adhering to reconfigure logic by using that camera interface helper function. But that's a ticket for another day.

2024-02-27 20:10 UTC, bhaney commented
> > Probably would add a test that explicitly expects the error with the absurdly large dimensions but according to our conversation about unit tests yesterday I can be swayed either way
> 
> So, for Config and Validation, the useful tests are in `resource.go` and `config.go` but i can add a in-driver test. The screenshots show the results of manual testing.
> 
> There is a crazy behavior where the resource construction seems to loop forever with a bad validation when I was expecting just five failures. I think that's because of the `resource.AlwaysRebuild` and cameras not adhering to reconfigure logic by using that camera interface helper function. But that's a ticket for another day.

Cameras don't "fail out" of reconfiguration because they have a lot of automatic re-connection logic that allows you to unplug one webcam and plug in another webcam without having to reconfigure the component. This was considered neat at the time of creating this feature. Stopping reconfiguration after 5 attempts would break a lot of re-connection logic that webcams currently have to keep the online despite network blips

2024-02-27 20:12 UTC, bhaney requested changes
just a small typo

2024-02-27 20:12 UTC, bhaney commented on components/camera/fake/camera.go
> +		return nil, errors.New("maximum supported pixel height or width for fake cameras is 4000 pixels")
text of 4000 doesn't match the actual limits of 10000

2024-02-27 20:32 UTC, randhid commented
> > > Probably would add a test that explicitly expects the error with the absurdly large dimensions but according to our conversation about unit tests yesterday I can be swayed either way
> > 
> > 
> > So, for Config and Validation, the useful tests are in `resource.go` and `config.go` but i can add a in-driver test. The screenshots show the results of manual testing.
> > There is a crazy behavior where the resource construction seems to loop forever with a bad validation when I was expecting just five failures. I think that's because of the `resource.AlwaysRebuild` and cameras not adhering to reconfigure logic by using that camera interface helper function. But that's a ticket for another day.
> 
> Cameras don't "fail out" of reconfiguration because they have a lot of automatic re-connection logic that allows you to unplug one webcam and plug in another webcam without having to reconfigure the component. This shows up on the app control panel as a frozen image, which then restarts when the camera is plugged back in, all without needing to re-configure. This was considered neat at the time of creating this feature. Stopping reconfiguration after 5 attempts would break a lot of re-connection logic that webcams currently have to keep the online despite network blips

That's okay - we can handle that logic async in the reconfigure function, and probably would be a better place for it to live anyway, and what we do for other sensors on bucket. That's a larger lift than what I would do immediately, but the current design does not block new implementations.

2024-02-28 19:47 UTC, bhaney approved these changes
LGTM

2024-03-06 18:42 UTC, merged