[APP-4566] Tag 'latest' release with build timestamp
viamrobotics/rdk pull request #3794
Opened 2024-04-10 21:00 UTC by ale7714

Use a sortable key for latest viam-server build so we can enable users to configure latest as release channel in Viam Agent config.

[APP-4566](https://viam.atlassian.net/browse/APP-4566)

2024-04-10 22:28 UTC, Otterverse requested changes
One potential issue (inline comments.)

2024-04-10 22:28 UTC, Otterverse commented on .github/workflows/staticbuild.yml
> +        sudo -Hu testbot bash -lc 'make RELEASE_TYPE="latest" BUILD_CHANNEL="${{date +%Y%m%d%H%M%S}}" static-release'
So I'm worried that the date here isn't going to match between different architectures. I'm not sure if that matters or not, but as arm64 and amd64 would be two different jobs, they'd run at slightly different times and thus it wouldn't be clear if/when things were the same "build" or not.

Ex: 
```
viam-server-20240410121314-arm64
viam-server-20240410121318-amd64
```

I think the correct answer would be have have a timestamp input to this workflow, so they'd both use the same one.

2024-04-11 17:45 UTC, ale7714 commented on .github/workflows/staticbuild.yml
> +    - name: Set Date Version (Latest)
ooof i see what you mean now, i'll add the new job

2024-04-11 20:16 UTC, Otterverse approved these changes
LGTM, but have to see if it runs correctly once you merge it. Fingers crossed.

2024-04-17 14:46 UTC, merged