Add Shutdown Command to Robot
viamrobotics/rdk pull request #4032
Opened 2024-06-03 20:33 UTC by danielbotros

### Description
**RSDK-6972:** Add a Shutdown command to robot
* `Shutdown` command, `ShutdownRequest`, and `ShutdownResponse` added to API in this [PR](https://github.com/viamrobotics/api/commit/4f9d14d067b9b7965fcb4e89d6185e9dc348c3cd)
* Ability to call `Shutdown()` added through Robot interface, client, and server. 
* A robot cannot shut itself down, it must be shutdown by its entry point process. In order for the robot to be able to shut itself down, it must have access to a callback function which allows it to call `cancel()` on it's original context. 
  * In order to accomplish this, a shutdown function (log of stack trace + `cancel()`) is binded to the robot options by adding a `shutdownCallback` field to the  robot options struct. This is set through `WithShutdownCallback()` in `entrypoint.go`
  * Robots now have a `shutdownCallback` field which is set during initialization through robot options. On `Shutdown()`, this callback is called to shutdown the robot, if it exists, otherwise it throws an error.  
    * May not exist since it is only binded when being started through `entrypoint.go `

### Testing
* A single integration test is added to `entrypoint_test.go` which starts the RDK as a separate process then calls `Shutdown()` and ensures it does not return an error and that there are no errors in the logs as the shutdown occurs.

2024-06-03 20:53 UTC, cheukt requested changes
looks good, some requests around better structure and additional tests

2024-06-03 20:53 UTC, cheukt commented on robot/client/client.go
> +func (rc *RobotClient) Shutdown(ctx context.Context) error {
can you add a test for this as well? add it through updating `injectRobot`

2024-06-03 20:53 UTC, cheukt commented on robot/server/server.go
> +	err := s.robot.Shutdown(ctx)
add a test through updating `injectRobot`

2024-06-03 20:53 UTC, cheukt commented on web/server/entrypoint.go
> +		bufSize := 1 << 20
factor this out so we aren't copying the code from https://github.com/viamrobotics/rdk/pull/4032/files#diff-780f3d307fb668fed30f86c777b47efbbd6848b5aa3282dc1958bc76b2f07ecbR343-R350

2024-06-03 20:53 UTC, cheukt commented on web/server/entrypoint_test.go
> +	t.Run("shutdown functionality", func(t *testing.T) {
make this a separate test

2024-06-04 16:26 UTC, maximpertsov commented on robot/impl/local_robot.go
> +	return errors.New("shutdown function not defined")
error is fine here - we should just document the behavior. we could also consider validating/requiring the shutdown "option" at an earlier step, but i think what you have is perfectly fine.

as an aside, long-term we should consider merging the server management logic into the robot itself... it's pretty confusing that robot has both a `Shutdown` and `Close` method now, where the former indirectly calls the latter at some point.

2024-06-04 17:32 UTC, danielbotros commented on robot/impl/local_robot.go
> +	return errors.New("shutdown function not defined")
added some more documentation outlining the command will throw an error if a shutdown callback isn't binded to the robot

I definitely agree, it makes sense why both exist but it is not intuitive at all on how/which to use as a user

2024-06-04 17:33 UTC, danielbotros commented on web/server/entrypoint_test.go
> +	t.Run("shutdown functionality", func(t *testing.T) {
all donezo

2024-06-04 19:06 UTC, benjirewis approved these changes
Looks good to me! 🫡  Thanks

2024-06-04 19:06 UTC, benjirewis commented on robot/client/client.go
> +// shutdown callback is not binded to robot options.
```suggestion
// Shutdown shuts down the robot. Will return a "shutdown function not defined error" if
// shutdown callback is not specified in robot options.
```
Nits.

2024-06-04 19:06 UTC, benjirewis commented on web/server/entrypoint_test.go
> +		test.That(t, logObserver.FilterLevelExact(zapcore.ErrorLevel).Len(), test.ShouldEqual, 0)
Nice 🧑‍🔧 .

2024-06-04 19:24 UTC, cheukt requested changes
small change in tests requested

2024-06-04 19:24 UTC, cheukt commented on robot/client/client_test.go
> +	test.That(t, err, test.ShouldBeNil)
this doesn't properly test that the client sends a message to the server - we should do something like https://github.com/viamrobotics/rdk/blob/main/components/arm/server_test.go#L84-L87 and maybe toggle a bool to indicate we reached the Shutdown func

2024-06-04 19:24 UTC, cheukt commented on robot/server/server_test.go
> +		_, err := server.Shutdown(context.Background(), &req)
same as above

2024-06-04 20:57 UTC, danielbotros commented on robot/client/client.go
> +// shutdown callback is not binded to robot options.
updated doc

2024-06-04 21:10 UTC, cheukt approved these changes
LGTM!

2024-06-04 21:45 UTC, maximpertsov commented on robot/impl/local_robot.go
> +	return errors.New("shutdown function not defined")
doc looks good!

2024-06-04 21:45 UTC, maximpertsov approved these changes

2024-06-05 14:31 UTC, merged