DOCS-2089: Add board API code samples
viamrobotics/rdk pull request #4132
Opened 2024-06-25 19:40 UTC by andf-viam

Add code samples to Board API GO methods, for:
- `Board` API itself
- `Analog` API
- `GPIOPin` API
- `DigitalInterrupt` API

Code samples sourced from live docs.viam.com reference page: https://docs.viam.com/components/board/#api

2024-06-27 16:52 UTC, andf-viam commented
@cheukt let me know if you'd like to see any changes -- just more code samples, all in `//` comments. Thanks so much!

2024-06-27 16:53 UTC, cheukt commented
tagging @randhid instead

2024-06-28 00:12 UTC, randhid requested changes

2024-06-28 00:12 UTC, randhid commented on components/board/board.go
> +//	names := myBoard.DigitalInterruptNames()
we will remove these once Status is gone - so I'd just not document them.

2024-06-28 00:12 UTC, randhid commented on components/board/board.go
> +//	// Get the value of the digital signal "my_example_analog" has most recently measured.
analog signal

2024-06-28 00:12 UTC, randhid commented on components/board/digital_interrupts.go
> +//	count, err := interrupt.Value(context.Background(), nil)
Type basic is a pi-only implementation. This is just how many times a digital interrupt has ticked.

2024-06-28 00:12 UTC, randhid commented on components/board/digital_interrupts.go
> +//	rolling_avg, err := interrupt.Value(context.Background(), nil)
Remove

2024-06-28 00:12 UTC, randhid commented on components/board/board.go
> +//	err = myBoard.StreamTicks(context.Background(), interrupts, ticksChan, nil)
show how a ticksChan can be made.

2024-06-28 16:06 UTC, randhid commented on components/board/board.go
> +//	// Show how a ticksChan can be made from the listed digital interrupts on pins 8 and 11.
```suggestion

```

2024-06-28 16:06 UTC, randhid commented on components/board/gpio_pin.go
> +//	// Get if it is true or false that the state of the pin is high.
This returns the duty cycle

2024-06-28 16:08 UTC, andf-viam commented on components/board/gpio_pin.go
> +//	// Get if it is true or false that the state of the pin is high.
```suggestion
//	// Returns the duty cycle.
```

2024-06-28 16:08 UTC, randhid approved these changes

2024-06-28 18:03 UTC, merged