RSDK-8699: Cannot go to gantry position 0.0, only 0.2+.
viamrobotics/rdk pull request #4354
Opened 2024-09-06 17:33 UTC by martha-johnston

- remove error margin to allow gantry to move to 0
- return more logs and errors for frontend

2024-09-06 17:37 UTC, penguinland approved these changes
LGTM! I like how straightforward the code changes are: it does exactly what the PR title says.

2024-09-06 17:42 UTC, oliviamiller approved these changes

2024-09-06 17:47 UTC, martha-johnston commented
> LGTM! I like how straightforward the code changes are: it does exactly what the PR title says.

lol thanks the last minute bucket review

2024-09-06 17:47 UTC, martha-johnston commented
@michaellee1019 if you're interested

2024-09-09 03:54 UTC, randhid requested changes
Please add tests to ensure we can move to 0 and the limit margin, this way we can verify that these cases are maintained  in the future.

2024-09-09 03:54 UTC, randhid commented on components/gantry/singleaxis/singleaxis_test.go
> +	test.That(t, err.Error(), test.ShouldContainSubstring, "cannot move past limit switch")
Why did the behaviour of these tests change?

2024-09-09 18:13 UTC, martha-johnston commented
> Please add tests to ensure we can move to 0 and the limit margin, this way we can verify that these cases are maintained in the future.

Added a test to 0, but limit margin is removed so we shouldn't need a test for that!

2024-09-09 18:41 UTC, martha-johnston commented
> We should test that we can go to the end of the limit - PositionB, but error if we go further.

added a test for going exactly to position b, but tests for going further already exist so I didn't add any more

2024-09-09 19:19 UTC, randhid approved these changes

2024-09-09 19:38 UTC, merged