Update dependabot.yml to joncha1
viamrobotics/rdk pull request #4361
Opened 2024-09-12 19:56 UTC by stevebriskin

2024-09-13 20:05 UTC, joncha1 requested changes
can you add [tpm@viam.com](mailto:tpm@viam.com)? if not can you also add Tenzing and Ian

2024-10-30 14:36 UTC, IanWhalen approved these changes

2025-06-02 15:58 UTC, dgottlieb commented
Closing this PR so dependabot tries again

2025-06-02 16:46 UTC, dgottlieb commented
@IanWhalen can you double check that's the right set of owners we want now? Or should we be closing the PR?

2025-06-04 14:33 UTC, dgottlieb commented
Poke @IanWhalen

2025-06-11 13:06 UTC, merged