RSDK-9591 - Kill all lingering module process before exiting
viamrobotics/rdk pull request #4657
Opened 2024-12-27 16:13 UTC by cheukt

This is part two of two PRs that will hopefully help with shutting down all module processes before viam-server exits.

This is still a draft as I'm looking for thoughts and ideas around making this better.

Before doing this, I looked into assigning module processes to the same process group as the viam server and just kill the process group. However, we already have each module and process assign to unique process groups, and we use that property to kill each modules and processes separately if necessary. Changing that behavior would be risky, so did not pursue that path further.

We could kill each process in mod manager directly using the exposed unixpid, but figured we could just do it within each managed process, that way we get support in windows as well. It does mean I added Kill() in a few interfaces, but it will hopefully be extensible in case anything else may need killing.

The idea behind this is for a Kill() call to propagate from the viam-server at the end of 90s, and we should not block on anything if possible. The Kill() does not care about the resource graph, only that we kill processes/module processes spawned by the server. I did not do the killing in parallel, since the calls will not block. I can see things racing with Close(), but I think the mitigation would be to make sure that kill/close is idempotent and will not panic if overlapping. This Kill() call does happen in the same goroutine that eventually calls log.Fatal, is that good enough for now or should we create a different goroutine so that we can guarantee that the viam-server exits by the 90s mark?

Ideas for testing? I've tested on a python module and observed that the module process does get killed, and would be good to test on setups where this is happening.

2024-12-31 21:22 UTC, dgottlieb commented on web/server/entrypoint.go
>  				case <-doneServing:
While we're here, I'd recommend removing this whole `case <-doneServing` stuff (and incidentally the select statement) and move straight to the killing/logging.

2024-12-31 21:22 UTC, dgottlieb commented on web/server/entrypoint.go
> +					if myRobot != nil {
If `myRobot` can be nil here -- this is a data race.

2024-12-31 21:22 UTC, dgottlieb commented on robot/impl/local_robot.go
> +	if r.manager != nil {
Can we justify this isn't a data race?

2025-01-02 17:24 UTC, cheukt commented on web/server/entrypoint.go
>  				case <-doneServing:
why is that? I thought the justification above for the code as it is makes sense

2025-01-02 17:24 UTC, cheukt commented on web/server/entrypoint.go
> +					if myRobot != nil {
would that be an issue? I can see that myRobot could have started some processes but not yet returned, but I don't know if we can protect against that completely.

2025-01-02 17:24 UTC, cheukt commented on robot/impl/local_robot.go
> +	if r.manager != nil {
r.manager could be nil if startup fails/hangs, but yes, it could also be a data race.

2025-01-06 21:10 UTC, dgottlieb commented on robot/impl/local_robot.go
> +	if r.manager != nil {
We talked offline -- I agree that the a mutex doesn't fix the "logical" race where we may observe the manager is nil a moment before it gets assigned. 

But TSAN/Go's data race detection will notice this. Strictly speaking if one has two threads reading and writing a variable/memory address at the same time:
```
X initialized to 0
| Writer       | Reader |
|--------------+--------|
| Write(X = 1) | Read X |
```

While our program may be OK with the reader seeing 0 or the reader seeing 1, it's not necessarily the case that for all architectures the Reader can only see 0 or 1.

2025-01-06 21:10 UTC, dgottlieb commented on robot/impl/resource_manager.go
> +	if manager.moduleManager != nil {
I suspect this can be a data race as well?

2025-01-06 21:10 UTC, dgottlieb commented on web/server/entrypoint.go
> +					if myRobot != nil {
Same remark as the other cases

2025-01-08 16:55 UTC, benjirewis commented on web/server/entrypoint.go
>  	utils.PanicCapturingGo(func() {
Would be awesome if this force shutdown goroutine was its own method/function as we've been doing for our various unnamed async lambdas.

2025-01-09 15:01 UTC, cheukt commented on web/server/entrypoint.go
> +					if myRobot != nil {
added some locking around this

2025-01-09 15:02 UTC, cheukt commented on robot/impl/local_robot.go
> +	if r.manager != nil {
looking at this again, this isn't a data race - there's no chance for Kill() to be called before r.manager is assigned (Kill() can only be called if robot exists, and robot only exists if r.manager is assigned)

2025-01-09 15:02 UTC, cheukt commented on robot/impl/resource_manager.go
> +	if manager.moduleManager != nil {
yep! added some locking around this

2025-01-09 15:08 UTC, dgottlieb commented on robot/impl/local_robot.go
> +	r.manager.Kill()
It feels a little awkward that localRobot.Kill only calls kill on the resource manager.

And the resource manager only calls kill on the mod manager.

And localRobot already has a handle on the modmanager. So why doesn't it call kill directly? Or just have the part that's about to do the log.Fatal/os.Exit call kill on the modmanager?

2025-01-09 15:10 UTC, dgottlieb commented on robot/impl/local_robot.go
> +	if r.manager != nil {
Great -- much prefer to be able to assume members are non-nil.

2025-01-09 15:16 UTC, cheukt commented on robot/impl/local_robot.go
> +	r.manager.Kill()
keeping the abstractions I think is better in the long run - the resource manager will eventually call kill on the process manager. 
the part that's about to do log.Fatal doesn't have a handle to the modmanager, since it only has access to the LocalRobot interface.

2025-01-09 15:19 UTC, dgottlieb commented on robot/impl/local_robot.go
> +	r.manager.Kill()
> keeping the abstractions I think is better in the long run

If I'm adding some plumbing from local robot -> modmanager, when should I use `localRobot.modmanager` directly and when should I add additional plumbing through `localRobot.manager`?

2025-01-09 15:50 UTC, dgottlieb commented on robot/impl/local_robot.go
> +	r.manager.Kill()
FWIW, I'm fine with leaving this as-is. The above is me just coming to the realization that there's some abstraction that I didn't know existed.

2025-01-10 15:45 UTC, cheukt commented
this is ready for full review! added 2 small-ish tests that test the expected behavior. hopefully they pass on CI or I might just skip them

2025-01-10 16:32 UTC, dgottlieb commented on web/server/entrypoint.go
> +					theRobotLock.Unlock()
I believe this is accidental?

2025-01-10 16:35 UTC, cheukt commented on web/server/entrypoint.go
> +					theRobotLock.Unlock()
thanks for catching!

2025-01-10 16:37 UTC, cheukt commented on module/modmanager/manager_test.go
> +		test.That(tb, logs.FilterMessageSnippet("Killing module").Len(),
not the most robust test, but using the Status() method didn't work

2025-01-10 16:41 UTC, dgottlieb approved these changes

2025-01-10 17:46 UTC, benjirewis requested changes
Looking good! Just some final nits...

2025-01-10 17:46 UTC, benjirewis commented on module/modmanager/manager.go
> +// Kill kills module processes. This is best effort as we do not
> Kill kills modules processes.

Per my nits on the other PR, we're technically killing module process groups here. Could we make sure that's at least clear in documentation here and wherever else we're calling `managedProcess.Kill` and describing what we're doing? The group vs. process thing led to some initial (and perhaps continued) confusion for me, so, while this looks pretty good code-wise, I'd love to not be confused looking back at this stuff.

2025-01-10 17:46 UTC, benjirewis commented on module/modmanager/manager_test.go
> +		test.That(tb, logs.FilterMessageSnippet("Killing module").Len(),
> Using the `Status()` method didn't work.

Any idea why? Still reported being alive?

2025-01-10 17:46 UTC, benjirewis commented on robot/impl/local_robot.go
> +	r.manager.Kill()
> localRobot.modmanager

I'm not aware of an existing `localRobot.modmanager` field? Or are you suggesting adding one?

2025-01-10 17:46 UTC, benjirewis commented on robot/impl/local_robot_test.go
> +	t.Skip()
I appreciate that this test exists, but is it even meaningful to have it around? A `t.Skip` with no TODO to unskip feels wrong to me. Or were you meaning to remove this `t.Skip`?

2025-01-10 17:46 UTC, benjirewis commented on robot/impl/resource_manager.go
> +	// modManagerLock controls access to the moduleManager
[nit] Can we just elaborate a bit on comment explaining that a `Kill` from local robot may try to access the module manager concurrently with resource manager accesses?

2025-01-10 20:15 UTC, cheukt commented on module/modmanager/manager_test.go
> +		test.That(tb, logs.FilterMessageSnippet("Killing module").Len(),
err is returning nil, so I assume so. Maybe a quirk of how it works on CI, because the test with Status() worked fine locally

2025-01-10 20:23 UTC, cheukt commented on robot/impl/local_robot.go
> +	r.manager.Kill()
I think @dgottlieb is asking whether he should use `localRobot.manager.modmanager`.

To @dgottlieb's question, I don't have a good answer. I feel like localRobot and resource manager are already a bit mangled, and I think adding the plumbing will end up making the unmangling slightly more manageable if we ever decide to do it

2025-01-10 20:27 UTC, cheukt commented on robot/impl/local_robot_test.go
> +	t.Skip()
it's meaningful to be able to run locally, but added a ticket as well https://viam.atlassian.net/browse/RSDK-9722

2025-01-10 20:42 UTC, cheukt commented on robot/impl/resource_manager.go
> +	// modManagerLock controls access to the moduleManager
added

2025-01-10 20:42 UTC, cheukt commented on module/modmanager/manager.go
> +// Kill kills module processes. This is best effort as we do not
updated comments

2025-01-10 20:45 UTC, benjirewis approved these changes
Thanks!

2025-01-10 21:05 UTC, merged